activities/PHQ-9/items/phq9_1.jsonld
activities/PHQ-9/items/phq9_10.jsonld
activities/PHQ-9/items/phq9_2.jsonld
activities/PHQ-9/items/phq9_3.jsonld
activities/PHQ-9/items/phq9_4.jsonld
activities/PHQ-9/items/phq9_5.jsonld
activities/PHQ-9/items/phq9_6.jsonld
activities/PHQ-9/items/phq9_7.jsonld
activities/PHQ-9/items/phq9_8.jsonld
activities/PHQ-9/items/phq9_9.jsonld
activities/PHQ-9/items/phq9_category.jsonld
activities/PHQ-9/items/phq9_total_score.jsonld
activities/PHQ-9/phq9_schema.jsonld

still a work in progress as i get a prototype UI up and running

wip: editing the jsonld files so they are json compliant

---

activities/NDA/items/interview_age.jsonld
activities/NDA/items/src_subject_id.jsonld
activities/NDA/items/subjectkey.jsonld
activities/PHQ-9/context.jsonld
activities/PHQ-9/items/phq9_1.jsonld
activities/PHQ-9/items/phq9_10.jsonld
activities/PHQ-9/items/phq9_category.jsonld
activities/PHQ-9/items/phq9_total_score.jsonld
activities/PHQ-9/items/question.jsonld
activities/PHQ-9/phq9_schema.jsonld
activities/PHQ-9/select_language.jsonld
activities/PHQ-9/time_interval.jsonld
activities/PHQ-9/valueConstraints.jsonld
activities/sample_instrument/items/multiple_choice.jsonld
activity-sets/ReproNim/nda-phq9.jsonld

reorganizing schema structure and refactoring as per discussion with satra.

continued refactorization

---

activities/NDA/items/gender.jsonld
activities/PHQ-8/valueConstraints.jsonld
activities/PHQ-9/valueConstraints.jsonld
activities/PHQ-9a/valueConstraints.jsonld
contexts/generic.jsonld

minor changes

---

activities/draw_task/draw_task_context.jsonld
activities/draw_task/draw_task_schema.jsonld
activities/draw_task/items/freehand.jsonld
activities/draw_task/items/freehand_valueConstraints.jsonld

adding a drawing task for mindlogger the mobile app

wip: adding a draw task

---

activities/NDA/nda_guid.jsonld
activity-sets/voice-pilot/README.md

- make upload birth certificate invisible for now
- updated readme in voice study

refactor voice study and nda schema

---

activities/NDA/nda_guid.jsonld

forgot to change the visibility item names!

---

activities/NDA/nda_context.jsonld

fix item name in nda context

---

activities/PHQ-9-LORIS/items/README.md
activities/PHQ-9-LORIS/items/phq9_1.jsonld
activities/PHQ-9-LORIS/items/phq9_10.jsonld
activities/PHQ-9-LORIS/items/phq9_2.jsonld
activities/PHQ-9-LORIS/items/phq9_3.jsonld
activities/PHQ-9-LORIS/items/phq9_4.jsonld
activities/PHQ-9-LORIS/items/phq9_5.jsonld
activities/PHQ-9-LORIS/items/phq9_6.jsonld
activities/PHQ-9-LORIS/items/phq9_7.jsonld
activities/PHQ-9-LORIS/items/phq9_8.jsonld
activities/PHQ-9-LORIS/items/phq9_9.jsonld
activities/PHQ-9-LORIS/items/phq9_category.jsonld
activities/PHQ-9-LORIS/items/phq9_total_score.jsonld
activities/PHQ-9-LORIS/phq9_context.jsonld
activities/PHQ-9-LORIS/phq9_schema.jsonld
activities/PHQ-9-LORIS/valueConstraints.jsonld

carbon copy of PHQ-9 activity so that any modifications done hereafter for LORIS compatibility in PHQ-9-LORIS is meaningful for reviewing

Copy PHQ-9 into PHQ-9-LORIS

---

activities/voice_task/multipart_audio_check.jsonld

Ref https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/125

:ambulance: :pencil: :shirt: Lint JSON

---

activities/PHQ-9-LORIS/items/phq9_0.jsonld
activities/PHQ-9-LORIS/items/phq9_1.jsonld
activities/PHQ-9-LORIS/items/phq9_10.jsonld
activities/PHQ-9-LORIS/items/phq9_2.jsonld
activities/PHQ-9-LORIS/items/phq9_3.jsonld
activities/PHQ-9-LORIS/items/phq9_4.jsonld
activities/PHQ-9-LORIS/items/phq9_5.jsonld
activities/PHQ-9-LORIS/items/phq9_6.jsonld
activities/PHQ-9-LORIS/items/phq9_7.jsonld
activities/PHQ-9-LORIS/items/phq9_8.jsonld
activities/PHQ-9-LORIS/items/phq9_9.jsonld
activities/PHQ-9-LORIS/items/phq9_category.jsonld
activities/PHQ-9-LORIS/items/phq9_total_score.jsonld
activities/PHQ-9-LORIS/phq9_context.jsonld
activities/PHQ-9-LORIS/phq9_page1.jsonld
activities/PHQ-9-LORIS/phq9_page2.jsonld
activities/PHQ-9-LORIS/phq9_schema.jsonld
contexts/generic.jsonld
items/not_answered.jsonld
schemas/Activity.jsonld
schemas/Field.jsonld

- adds "page" and "section"
- adds static header element, inputType: "header"
- adds static scoring field, inputType: "static" (question and score gets rendered as non-input text element aka static)
- add "required"
- change scoring/branching logic formulas to fit [LParse](https://gitlab.com/zainvirani/LParse) syntax (based on RedCap)
**please don't merge before I change all the URLs back to master branch's**

Add "Sub-activity" LayoutElement level

---

contexts/generic.jsonld

refactor generic context

---

activities/MedicalHistory-LORIS/items/README.md
activities/MedicalHistory-LORIS/items/medicalhistory_1.jsonld
activities/MedicalHistory-LORIS/items/medicalhistory_2.jsonld
activities/MedicalHistory-LORIS/items/medicalhistory_21.jsonld
activities/MedicalHistory-LORIS/items/medicalhistory_21d.jsonld
activities/MedicalHistory-LORIS/items/medicalhistory_2a.jsonld
activities/MedicalHistory-LORIS/items/medicalhistory_7.jsonld
activities/MedicalHistory-LORIS/items/medicalhistory_7a.jsonld
activities/MedicalHistory-LORIS/items/medicalhistory_hospitalized.jsonld
activities/MedicalHistory-LORIS/items/medicalhistory_incident.jsonld
activities/MedicalHistory-LORIS/medicalhistory_concussion_table.jsonld
activities/MedicalHistory-LORIS/medicalhistory_context.jsonld
activities/MedicalHistory-LORIS/medicalhistory_page1.jsonld
activities/MedicalHistory-LORIS/medicalhistory_page2.jsonld
activities/MedicalHistory-LORIS/medicalhistory_page3.jsonld
activities/MedicalHistory-LORIS/medicalhistory_schema.jsonld
activities/MedicalHistory-LORIS/medicalhistory_sectionA.jsonld
activities/MedicalHistory-LORIS/medicalhistory_sectionB.jsonld
activities/MedicalHistory-LORIS/medicalhistory_sectionC.jsonld
activities/MedicalHistory-LORIS/medicalhistory_sectionD.jsonld
contexts/generic.jsonld
items/age_text.jsonld
value_constraints/yes_no.jsonld

LORIS Medical History instrument

Table element implementation example

---

activities/MedicalHistory-LORIS/items/medicalhistory_2a.jsonld
activities/MedicalHistory-LORIS/medicalhistory_sectionD.jsonld
activities/PHQ-9-LORIS/phq9_schema.jsonld

Special char throwing me an error when fetching the json. Please merge and remove!

Remove special char to remove json parsing error

---

activities/MedicalHistory-LORIS/medicalhistory_concussion_table.jsonld

@sanuann hi sanu, here's another one sorry!

remove trailing comma

---

value_constraints/yes_no.jsonld

@sanuann hi sanu, i found another typo! thanks

remove comma in yes_no.jsonld

---

activities/MedicalHistory-LORIS/medicalhistory_schema

Add medicalhistory string to concussion table

---

contexts/generic
examples/protocols/protocol1.jsonld
validation/ActivityShape.ttl
validation/ProtocolShape.ttl

@sanuann - i think this has to be this way for the constants.

fix: constants

---

docs/index.md

[DOC] add a how to cite in doc

---

contexts/reproschema
linkml-schema/reproschema.yaml
linkml-schema/reproschema_linkml.py

adding `CreativeWork` to `ResponseOption`, dealing with dict-form of compute

additional changes based on testing library

---

mkdocs.yml

- closes #484
also adds a way to easily edit specific pages

[MAINT] implement dark mode

---

linkml-schema/reproschema.yaml

adding a component to the schema to allow for proprietary schemas to be represented

add proprietary flag to activities

---

linkml-schema/reproschema.yaml

fixing: https://github.com/ReproNim/reproschema-py/issues/47

adding preamble to Protocol, removing TODOs

---

macros/__init__.py
macros/macros.py

apply linting rules on recently merged PRs

[STY] apply linting on all files
